arf:arf.v arf_variance.v arf_accurate.v interface.v parameters.v arf_variance_0.v
	vcs  +incdir+../resources/AMA_appr4_32bit_8appr+../resources/jiehan_bth -sverilog -ntb_opts dtm +v2k arf.v -o $@
r:arf
	./arf +T=20000

