arf:arf.v arf_variance.v arf_accurate.v interface.v parameters.v
	vcs  +incdir+../resources/AMA_appr4_32bit_8appr+../resources/jiehan_bth -sverilog -ntb_opts dtm +v2k arf.v -o $@
run:arf
	./arf +T=1000

